# Generated by Django 3.2.7 on 2024-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_examples', '0003_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('colour', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_tags',
            field=models.ManyToManyField(blank=True, to='cards_examples.PaymentTag'),
        ),
    ]
